name: Actions Build OpenWrt

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:  
      version:
        description: 选择 OpenWrt 版本
        required: false
        default: "24.10.0"
        type: choice
        options:
          - 23.05.5
          - 24.10.0
      
      source_name:
        description: 选择编译源码
        required: false
        default: "all"
        type: choice
        options:
          - all
          - subscribe
          - sseconsole
          - wsconsole
          - docker-web
          - wake-on-lan
          - mddns-script
          - bemfa-server
          - api
          - wxpusher
          - sub
          - openssl.cgi
          - v2ray.cgi
          - page.cgi
          - sub.cgi
          - netlink
      
      upx:
        description: 是否upx压缩
        default: true
        type: boolean
      
      cnb:
        description: 是否上传到(CNB)仓库
        default: true
        type: boolean
        
      pack:
        description: 是否打包(TAR.GZ)
        default: false
        type: boolean
    
jobs:
  Call-Build-OpenWrt:
    name: build ${{ inputs.source_name }}
    uses: ./.github/workflows/Call-Build-OpenWrt.yml
    secrets: inherit
    with:
      version: ${{ inputs.version }}
      source_name: ${{ inputs.source_name }}
      upx: ${{ inputs.upx }}
      pack: ${{ inputs.pack }}
      cnb: ${{ inputs.cnb }}